GET http://localhost:3000/registro

###

POST http://localhost:3000/users/registrar
content-type: application/json

{
    "name": "prueba",
    "username": "TEST",
    "email":"prueba@hotmail.es",
    "password":"1234"
}

###


POST http://localhost:3000/users/login
content-type: application/json

{
    "username": "TEST",
    "email":"prueba@hotmail.es",
    "password":"1234"
}

###


GET http://localhost:3000/users/confirm/5f41356602f0292ad4c5232c


###

POST http://localhost:3000/users/logout
    authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQxMzU2NjAyZjAyOTJhZDRjNTIzMmMiLCJpYXQiOjE1OTgxMTE2NzgsImV4cCI6MTY2MTIyNjg3OH0.Gq1GZEp3e01ybV1BgZ2KAizJ40IrfvrYz3eMq0WEl4E
    
###