POST https://becomm.herokuapp.com/users/registrar
content-type: application/json

{
    "name": "prueba",
    "username": "TEST",
    "email":"prueba@hotmail.es",
    "password":"1234"
}


###


POST https://becomm.herokuapp.com/users/login
content-type: application/json

{
    "username": "TEST",
    "email":"prueba@hotmail.es",
    "password":"1234"
}

###


GET https://becomm.herokuapp.com/users/confirm/5f474b5d21125a00175c612a


###


PUT https://becomm.herokuapp.com/users/actualiza/5f474b5d21125a00175c612a
content-type: application/json

{
    "name": "Prueba generica"
}


###


DELETE https://becomm.herokuapp.com/users/borra/5f474b5d21125a00175c612a



###

POST https://becomm.herokuapp.com/users/logout
    authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjQxMzU2NjAyZjAyOTJhZDRjNTIzMmMiLCJpYXQiOjE1OTg1MDYxNDAsImV4cCI6MTY2MTYyMTM0MH0.pnKPS5pvG-OejqLybpyi957FfgXMb3-jvbFwqblykqw
    
###