
GET http://localhost:3000/categorias/listado


###


GET http://localhost:3000/categorias/listadoconproductos


###

GET http://localhost:3000/categorias/porproducto/5f645e4e280d783ce463ebda


###


POST http://localhost:3000/categorias/inserta
content-type: application/json

{
    "name": "Abrigos"
}


###


PUT http://localhost:3000/categorias/5f6395b1192b5a15d0637f6d
content-type: application/json

{
    "name": "Abrigos calefactables"
}


###


DELETE http://localhost:3000/categorias/5f6395b1192b5a15d0637f6d
content-type: application/json
