
GET http://localhost:3000/categorias/listado


###

POST http://localhost:3000/categorias/inserta
content-type: application/json

{
    "name": "Accesorios"
}


###


PUT http://localhost:3000/categorias/5f4d5201a589435690d8bb31
content-type: application/json

{
    "name": "Abrigos calefactables"
}


###


DELETE http://localhost:3000/categorias/5f4f45b27ba64a2d0467a375
content-type: application/json

{
    "name": "Abrigos calefactables"
}