POST http://localhost:3000/productos/inserta
content-type: application/json

{
    "name": "Abrigo calefactable",
    "description" : "abrigo con calefacción incorporada. 3 posibles temperaturas. Nota: Requiere un PowerBank,",
    "price_wo_VAT" : 67,
    "VAT" : 21,
    "image_path" : "https://tubkala.com/wp-content/uploads/2020/03/ParkaCalefactableHombre.jpg",
    "stock" : 2,
    "categories" : "5f4d5201a589435690d8bb31",
    "userId" : "5f2e7f3d7b1e580017568a32"
}


###


PUT http://localhost:3000/productos/5f4d555021b10e58d8f4c3d4
content-type: application/json

{
    "price_VAT": 79.99
}


###


GET http://localhost:3000/productos/listado
