POST http://localhost:3000/productos/inserta
content-type: application/json

{
    "name": "Calcetines Técnicos CoolMax Low Joluvi",
    "description" : "<h2>>Calcetines técnicos.</h2><ul><li>Zonas acolchadas que protegen de rozaduras.</li><li>Zona de ajuste de control de presión</li><li>Durabilidad excepcional gracias a sus zonas reforzadas.</li><li>Uniones de costura super planas que reducen las áreas de fricción.</li></ul>",
    "price_VAT" : 5.95,
    "VAT" : 21,
    "image_path" : "https://tubkala.com/wp-content/uploads/2020/07/230666_CoolmaxLow_01.jpg",
    "stock" : 9,
    "categories" : ["5f4f45b27ba64a2d0467a375", "5f511acc75706836d4411c6c"],
    "userId" : "5f2e7f3d7b1e580017568a32"
}


###

POST http://localhost:3000/productos/inserta
content-type: application/json

{
    "name": "Mochila Joluvi Hydro 5",
    "description" : "<h2>>Mochila Joluvi Hydro 5</h2><ul><li>Capacidad de la mochila: 5 l.</li><li>Peso: 350 gr.</li><li>Medidas: 37x9x19 cm</li><li>Material de la mochila: Poliéster Ripstop</li><liMaterial de la bolsa de agua: TPU</li></ul>",
    "price_VAT" : 29.90,
    "VAT" : 21,
    "image_path" : "https://tubkala.com/wp-content/uploads/2018/10/233417_HYDRO_5_01-62-1.jpg",
    "stock" : 9,
    "categories" : ["5f4f45b27ba64a2d0467a375", "5f677f36b4cbb83ffc414b66"],
    "userId" : "5f2e7fd183134e0017cc978b"
}


###



PUT http://localhost:3000/productos/5f4d547b21b10e58d8f4c3d3
content-type: application/json

{
    "price_VAT": 39.95
}

###

PUT http://localhost:3000/productos/5f4fbff47b4ac040e85ec558
content-type: application/json

{
    "categories" : ["5f4f3ebaed0649428c0f41e4", "5f4d547b21b10e58d8f4c3d3"]
}

###


DELETE  http://localhost:3000/productos/5f51266ef992b35b90040d84


###

GET http://localhost:3000/productos/nombre/5f4d555021b10e58d8f4c3d4


###


GET http://localhost:3000/productos/listado

###


GET http://localhost:3000/productos/vendedor/5f2e7f3d7b1e580017568a32

###


GET http://localhost:3000/productos/categoria/5f4f3ebaed0649428c0f41e4

###


GET http://localhost:3000/productos/segunventas


###

GET http://localhost:3000/productos/porpreciomenor


###

GET http://localhost:3000/productos/porpreciomayor

###

GET http://localhost:3000/productos/pornombre
