
POST http://localhost:3000/factura/nueva
content-type: application/json

{
    "OrderId": "5f5521056bb3010f7419172c",
    "address":"calle Vieja, 5; 28850 - Torrejon de Ardoz - Madrid"
}

###

GET http://localhost:3000/factura/5f6bc5ab89ecf55b5047b56e


###

PUT http://localhost:3000/factura/modificar/5f6bcad0567f5739b440a773
content-type: application/json

{
    "address":"Calle Nueva, 15; 28850 - Torrejón de Ardoz - Madrid"
}