POST http://localhost:3000/pedidos/nuevo
content-type: application/json

{
    "products": [{"_id" : "5f677f6bb4cbb83ffc414b67", "cantidad" : 2},
                 {"_id" : "5f4fc110b3df514424fe1bbc", "cantidad" : 1}],
    "userId" : "5f2e7fd183134e0017cc978b"
}

###

GET http://localhost:3000/pedidos/info/5f5229d4b9270a6634ec11bc


###

GET http://localhost:3000/pedidos/cliente/5f2a98352be6140017ba697c

###

POST http://localhost:3000/pedidos/pagado
content-type: application/json

{
    "id": "5f51e86f1fc69b4724bc73f1"
}


###

POST http://localhost:3000/pedidos/enviado
content-type: application/json

{
    "id": "5f51e86f1fc69b4724bc73f1"
}